name: realtime_chat_app
description: A Flutter RealtimeChat application using Firebase
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  bloc: ^9.1.0
  cloud_firestore: ^6.1.0
  device_preview: ^1.2.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  example:
    path: packages/realtimechat_uikit/example
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  go_router: ^16.3.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  random_string: ^2.3.1
  realtimechat_uikit:
    path: packages/realtimechat_uikit
  rename_app: ^1.6.5
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
dev_dependencies:
  build_runner: ^2.10.1
  change_app_package_name: ^1.5.0
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  assets:
    - assets/images/
  generate: true
  uses-material-design: true

lint_staged:
  'lib/**.dart': dart format fix && dart fix --apply